### ISSUE TITLE
Turn single values to range, enable intervals.power-range

### ISSUE THREAD

**Issue by dduffey** [freekode/tp2intervals#61]
When importing from TP to Internvals.icu to use on garmin it would be handy to convert single value steps (like power) into power ranges.  Garmin complains if power is off just by 1 watt otherwise.  There appears to be a tp2i UI to do this w/ intervals.power-range.

I am opening this issue just for tracking to know when the power range feature is implemented for training peaks -> intervals.icu.

Thanks you for such a great project and super happy this works on my Linux based bike PC.

**Comment by freekode** [comment]
`intervals.power-range` is used only when the app gets workouts from Intervals, to copy to TP.
As I understand you have steps with single value in TP. You copy them to Intervals and sync to your Garmin?

**Comment by dduffey** [comment]
Yes, that is correct.  My coach uses TP and I use a garmin, and prefer intervals myself.  So it would be nice if single value steps in workouts some across as a range to intervals so that garmin doesn't complain about hitting the exact value.

**Comment by dduffey** [comment]
[2024-04-16_Clark-Trai.zip](https://github.com/freekode/tp2intervals/files/14997042/2024-04-16_Clark-Trai.zip)

I tried 0.5.6 but it didn't seem to turn single values into a range, I have the default setting in the config as "10".  I've attached an example fit file downloaded from TP.  It has steps that look like this:

Ramp up in 4 steps

3 min @ 69 W
1 Active Recovery
2 min @ 82 W
2 Endurance
2 min @ 96 W
2 Endurance
3 min @ 123 W
3/4 Sweet Spot

**Comment by freekode** [comment]
`intervals.power-range` only used when you copy workouts from Intervals to TP, it is not used in your case.
As I understand, you have workouts with single target values in TP. Before the fix, during copying from TP to Intervals were mapped to targets with rage (TP 140w -> Intervals 140-140w).
After the fix such targets will now be mapped as single value target (TP 140w -> Intervals 140w). Now you can use Intervals integrated sync configuration for Garmin. Go to https://intervals.icu/settings, in you Garmin configuration you will have similar to this
![image](https://github.com/freekode/tp2intervals/assets/940893/1b53d1d6-795d-466b-8e8f-7f86c9fbd5ca)
There you can set power range for workout synced from Intervals to Garmin.
Explanation from David https://forum.intervals.icu/t/api-access-to-intervals-icu/609/389
Hope it helps

**Comment by dduffey** [comment]
Awesome, thank you for making this tool.
